name: Warrensburg Bike Rally
favicon: null
layout_spectrum: 0.21058
typography_spectrum: 0.55567
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1a1e29'
    - '#2f468a'
    - '#7d9cdf'
    - '#6d707c'
  brandStrength: 0.6875
  lightness: 0.718724672216922
  saturation: 0.3434001284185797
  rhythmicContrast: 0.1311979682650417
purpose: []
